about_tab <- tabItem(tabName="about",
  h1("About this application"),
  fluidRow(
    box(
      title="What this application is meant for",
      width=12,
      "This application allows to investigate data sets of DI RNAs, which",
      "contain a big deletion in the middle of the original/wild-type",
      "sequence. This deletion is described in the corresponding data set by",
      "a Start and an End point."
    ),
    box(
      title="Overview about the different tabs",
      width=12,
      tags$ol(
        tags$li(tags$b("Select/Load Dataset"),
          ": Select a dataset from a list of given influenza strains or",
          "upload a new custom dataset. When uploading a custom dataset the",
          "FASTA files of the singel segments have provided by the user for",
          "some of the functionalities."
        ),
        tags$li(tags$b("Inspect single datapoint"),
          ": Gives detailed information about a single entry of the dataset.",
          "Entry needs to be selected at the bottom of the 'Select/Load",
          "Dataset' tab"
        ),
        tags$li(tags$b("Select segment"),
          ": This selection lets the user decide which of the eight segments",
          "will be used in the following three tabs."
        ),
        tags$li(tags$b("Lengths and Locations"),
          ": Includes a mapping of the locations of the start and end",
          "onto the full length segments. Also includes a histogram with the",
          "length of the deleted sequence, the bin size can be adjusted by",
          "the user"
        ),
        tags$li(tags$b("Nucleotide Distribution"),
          ": Shows the relative occurrence of the four nucleotides (Adenin",
          "Cytosin, Guanin and Uracil) directly before and after the deletion",
          "site. An expected distribution is calculated using a sampling",
          "approach which generates random deletion sites. The observed and",
          "expected values are compared by a binomial test."
        ),
        tags$li(tags$b("Direct Repeats"),
          ": Provides a comparision of the expected and observed number of",
          "direct repeats. The expected values are generated by a sampling",
          "approach. They are compared by a XXXXXXXXXX test.", 
        ),
        tags$li(tags$b("Linear Regression"),
          ": Indicates the connection of the wild-type segment lenght and the",
          "number of deletions that can be observed. It uses linear",
          "regression to show the correlation of the two variables and gives",
          "an estimated segment length (which is the intersection with the",
          "x-axis)."
        ),
        tags$li(tags$b("About"),
          ": Provides more detailed information about DIPs, the usage of the",
          "application, tipps for users and contact information."
        ),
      )
    ),
    box(
      title="Sources of the given datasets:",
      width=12,
      tableOutput("dataset_info_table")
    ),
    box(
      title="How to enter a custom dataset?",
      width=12,
      strong("General Info:"),
      tags$ol(
        tags$li("Custom datasets need to be in *.csv format."),
        tags$li("They have exactly four columns."),
        tags$li("Ordering of the four columns is crucial!"),
      ),
      strong("Example dataset:"),
      br(),
      "including correct order and naming of the headers",
      tags$table(border=2, width="100%",
        tags$tbody(
          tags$tr(
            tags$td(""),
            tags$td(strong("Column 1")),
            tags$td(strong("Column 2")),
            tags$td(strong("Column 3")),
            tags$td(strong("Column 4"))
          ),
          tags$tr(
            tags$td(strong("header names")),
            tags$td(tags$i("Segment")),
            tags$td(tags$i("Start")),
            tags$td(tags$i("End")),
            tags$td(tags$i("NGS_read_count"))
          ),
          tags$tr(
            tags$td(strong("column data type")),
            tags$td("character (string)"),
            tags$td("integer"),
            tags$td("integer"),
            tags$td("integer")
          ),
          tags$tr(
            tags$td(strong("description")),
            tags$td("Name of the segment that the DI RNA is coming from"),
            tags$td("Start position of the deletion site"),
            tags$td("End position of the deletion site"),
            tags$td("Number of counts in the NGS data of this specific DI RNA sample")
          )
        )
      )
    ),
    box(
      title="What are 'Direct Repeats'?",
      width=12,
      "The sequence of the RNA before the starting point and end point can be",
      "the same (is repeated). If this is so it is called a 'direct repat'.",
      "Direct Repeats can be of different length and are disscussed to be a",
      "driving factor in the generation of de novo DI RNAs.",
      br(),
      tags$img(src="direct_repeats.png"),
      br(),
      "The actual Start and End point of a DIP that has a direct repeat",
      "longer than 0 can not be determined certainly. In the given image a",
      "direct repeat of length 3 is given. There are four possible ways on",
      "how it could have been created during the experiment. If n is the",
      "length of the direct repeat, there are always n+1 options on how it",
      "could have been created."
    ),
    box(
      title="Contact information",
      width=12,
      "To get into contact with the developement team open a new",
      tags$a(href="https://github.com/LohmannJens/DIP-DSA/issues", "Issue"),
      "on GitHub. They can help you with more detailed questions and are open",
      "for new ideas and features."
    )
  )
)
