about_tab <- tabItem(tabName="about",
  h1("About this application"),
  fluidRow(
    box(
      title="What this application is meant for",
      width=12,
      "This application allows to investigate datasets of DI RNAs, which",
      "contain a big deletion in the middle of the original/wild-type",
      "sequence. This deletion is described in the corresponding datasets by",
      "a start and an end point."
    ),
    box(
      title="Overview about the different tabs",
      width=12,
      tags$ol(
        tags$li(tags$b("(Up-)load dataset:"),
          "Select a dataset from a list of given influenza strains or",
          "upload a new custom dataset. When uploading a custom dataset the",
          "FASTA files of the single segments need to be provided by the user",
          "for some of the functionalities."
        ),
        tags$li(tags$b("Dataset overview:"),
          "Shows statistical parameters about the NGS couunt of the selected",
          "dataset. Also provides a table where single data points can be",
          "viewed and selected"
        ),
        tags$li(tags$b("Inspect single datapoint:"),
          "Gives detailed information about a single entry of the dataset.",
          "The entry needs to be selected at the bottom of the 'Dataset",
          "overview' tab"
        ),
        tags$li(tags$b("Select segment:"),
          "This dropdown menu lets the user decide which of the eight",
          "segments will be used in the following four tabs."
        ),
        tags$li(tags$b("Lengths and locations:"),
          "Includes a mapping of the locations of the start and end onto",
          "the full length segment. Also includes a histogram with the length",
          "of the deleted sequence. The bin size can be adjusted by the user.",
          "A third plot includes a comparision of the length of the 3' and 5'",
          "ends."
        ),
        tags$li(tags$b("Nucleotide distribution:"),
          "Shows the relative occurrence of the four nucleotides (Adenine,",
          "Cytosine, Guanine and Uracil) directly before and after the",
          "deletion site. An expected distribution is calculated using a",
          "sampling approach which generates random deletion sites. The",
          "observed and expected values are compared by a binomial test."
        ),
        tags$li(tags$b("Direct repeats:"),
          "Provides a comparision of the expected and observed number of",
          "direct repeats. The expected values are generated by a sampling",
          "approach. They are compared using the wilcox test.", 
        ),
        tags$li(tags$b("Motif search:"),
          "This tab allows the user to search for motifs in the selected",
          "sequence. It shows where on the sequence a match is found and puts",
          "this into correlation with the location of the deletion sites. It",
          "also provides an overview of all matches"
        ),
        tags$li(tags$b("Linear regression:"),
          "Indicates the connection of the wild-type segment length and the",
          "number of deletions that can be observed. It uses linear",
          "regression to show the correlation of the two variables and gives",
          "an estimated segment length (which is the intersection with the",
          "x-axis)."
        ),
        tags$li(tags$b("NP density:"),
          "Maps the deletion sites to areas of high NP density, that need to",
          "be provided by the user. Shows where those areas are located in",
          "correspondence to the deletion sites and performs an analysis if",
          "the deletions occur more/less often than compared to randomly",
          "samplesd data. The default values of high NP areas are for strain",
          "A/Californa/07/2009.",
        ),
        tags$li(tags$b("About:"),
          "Provides more detailed information about DIPs, the usage of the",
          "application, tipps for users and contact information."
        ),
      )
    ),
    box(
      title="Sources of the given datasets:",
      width=12,
      tableOutput("dataset_info_table")
    ),
    box(
      title="How to enter a custom dataset?",
      width=12,
      strong("General info:"),
      tags$ol(
        tags$li("Custom datasets need to be in *.csv format."),
        tags$li("They have exactly four columns."),
        tags$li("Ordering of the four columns is crucial!"),
      ),
      strong("Example dataset:"),
      br(),
      "(Including correct order and naming of the headers)",
      tags$table(border=2, width="100%",
        tags$tbody(
          tags$tr(
            tags$td(""),
            tags$td(strong("Column 1")),
            tags$td(strong("Column 2")),
            tags$td(strong("Column 3")),
            tags$td(strong("Column 4"))
          ),
          tags$tr(
            tags$td(strong("header names")),
            tags$td(tags$i("Segment")),
            tags$td(tags$i("Start")),
            tags$td(tags$i("End")),
            tags$td(tags$i("NGS_read_count"))
          ),
          tags$tr(
            tags$td(strong("column data type")),
            tags$td("character (string)"),
            tags$td("integer"),
            tags$td("integer"),
            tags$td("integer")
          ),
          tags$tr(
            tags$td(strong("description")),
            tags$td("Name of the segment that the DI RNA is coming from"),
            tags$td("Start position of the deletion site"),
            tags$td("End position of the deletion site"),
            tags$td("Number of counts in the NGS data of this specific DI RNA",
              "sample"
            )
          )
        )
      )
    ),
    box(
      title="What are 'direct repeats'?",
      width=12,
      "The sequence of the RNA before the starting point and end point can be",
      "the same (is repeated). If this is the case it is called a 'direct",
      "repat'. Direct repeats can be of different length and are disscussed",
      "to be a driving factor in the generation of DI RNAs.",
      br(),
      tags$img(src="direct_repeats.png"),
      br(),
      "The actual start and end point of a DIP that has a direct repeat",
      "longer than 0 can not be determined certainly. In the given image a",
      "direct repeat of length 3 is given. There are four possible ways on",
      "how it could have been created during the experiment. If n is the",
      "length of the direct repeat, there are always n+1 options on how it",
      "could have been created."
    ),
    box(
      title="Contact information",
      width=12,
      "To get into contact with the developement team open a new",
      tags$a(href="https://github.com/LohmannJens/DIP-DSA/issues", "issue"),
      "on GitHub. There you can get help with more detailed questions and",
      "come up with new ideas and features."
    )
  )
)
